### ISSUE TITLE
GUI doesn't show:  ValueError: Reference at 'refs/heads/master' does not exist

### ISSUE THREAD

**Issue by ViktorNova** [rhetr/nsm-git#1]
Very cool project! 
The GUI is not showing for me. I'm getting this error:

`ValueError: Reference at 'refs/heads/master' does not exist`

I checked, and .git/refs/heads/ in the session directory is indeed empty, even after saving the client and the session

**Comment by rhetr** [comment]
hm, I have no idea why this is happening...can you pull the latest code and check the output of nsm-git.log?

**Comment by ViktorNova** [comment]
Sorry I missed this - here is the error I get in the console

```
Traceback (most recent call last):
  File "/home/stagecraft/Dev/nsm-git-rhetr/nsm-git", line 27, in initUI
    self.ui.initUI(str(repo))
  File "/home/stagecraft/Dev/nsm-git-rhetr/NSMGitUI.py", line 49, in initUI
    self.list = CommitList(git.Repo(repo))
  File "/home/stagecraft/Dev/nsm-git-rhetr/NSMGitUI.py", line 30, in __init__
    self.refreshRepo()
  File "/home/stagecraft/Dev/nsm-git-rhetr/NSMGitUI.py", line 34, in refreshRepo
    commits = list(self.repo.iter_commits())
  File "/usr/lib/python2.7/dist-packages/git/repo/base.py", line 423, in iter_commits
    rev = self.head.commit
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 168, in _get_commit
    obj = self._get_object()
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 161, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 115, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 142, in _get_ref_info
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

and here's the log

```
begin log
server capabilities: :server-control:broadcast:optional-gui:
session dir is /home/stagecraft/NSM Sessions/ZZZ----DEV/nsm-git
attempting to commit... created git repo... nothing to be done.
```

And here is the output of ``ls -R .git`1` from the test session directory. There was no .git folder previously:

```
.git:
branches  config  description  HEAD  hooks  info  objects  refs

.git/branches:

.git/hooks:
applypatch-msg.sample  commit-msg.sample  post-update.sample  pre-applypatch.sample  pre-commit.sample  prepare-commit-msg.sample  pre-push.sample  pre-rebase.sample  update.sample

.git/info:
exclude

.git/objects:
info  pack

.git/objects/info:

.git/objects/pack:

.git/refs:
heads  tags

.git/refs/heads:

.git/refs/tags:
```

Thanks!
